# Generated by Django 5.2 on 2025-04-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmanagement',
            name='last_checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
